version: '3'

services:
  db_refurbish:
    image: mongo:4.2
    command: mongod --port ${DB_PORT}
    container_name: db_refurbish
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}

  application_refurbishs:
    command: npm start
    build: .
    env_file:
      - .env
    depends_on:
      - db_refurbish
    links:
      - db_refurbish
    ports:
     - ${SERVER_PORT}:3000
    volumes:
      - .:/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

